name: Code analysis

on:
  pull_request:
    branches: [ master ]
    paths-ignore:
      - 'docs/**'
      - '**.md'
  push:
    branches: [ master ]
    paths-ignore:
      - 'docs/**'
      - '**.md'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install test dependencies
        run: |
          pip install -e .[dev]
      
      - name: Run unit tests with coverage
        # We have to rename the path in coverage.xml since Sonar is run in Docker
        # and has a different view of the file system
        run: |
          pip install pytest-cov
          python -m pytest tests/unit/ --cov=ennemi --cov-report=xml --junit-xml=test-results.xml
          sed 's/\/home\/runner\/work\/ennemi\/ennemi/\/github\/workspace/g' coverage.xml > coverage-mod.xml

      - name: Run type checker
        run: |
          python -m mypy ennemi/ tests/unit tests/integration tests/pandas
      
      - name: Run Sonar code analysis
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
