name: Continuous Integration

on:
  pull_request:
    branches: [ master ]
    paths-ignore:
      - 'docs/**'
      - '**.md'

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # Save a bit of resources by running only some combinations
        # macOS is tested on ARM only since GitHub no longer provides x64 runners on free tier
        # There is additionally a free-threaded run on Ubuntu -- for stable release, test other OSes too
        include:
          - os: ubuntu-latest
            python-version: '3.14'
          - os: ubuntu-latest
            python-version: '3.14t'
          - os: windows-latest
            python-version: '3.12'
          - os: macos-26
            python-version: '3.13'


    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install test dependencies
        run: |
          pip install -e .[dev]
      
      - name: Run all tests
        run: |
          python -m pytest . --junit-xml=test-results.xml
          
      - name: Run type checker
        run: |
          python -m ty check ennemi tests
